#!/usr/bin/env python3
"""triple_index.py — OCI/CAI/CSI, instantiated from Kabashkin 2026b (OC-1).

Source of truth: Kabashkin, I. (2026). "Reusable Cognitive Digital Twins",
Information 17(3):255 (biblio [06]; D10). Formulas implemented verbatim:

    OCI(t) = 1 − (1/|C_Ω|) · Σ_i I[c_i(Ω, ŝ(t)) = violated]
        C_Ω = set of ontology admissibility constraints (type consistency,
        part-whole, unit compatibility, causal admissibility); I[·] indicator.
        (paper eq. for ontology consistency index)

    CAI(t) = max_{y_k ∈ Y(t)} sim[ŝ(t), y_k(t)]
        Y(t) = scenarios generated by the generative modality; sim = domain-
        specific similarity (we use cosine over the state vector).

    CSI(t) = q(t) · max_{y_k ∈ Y(t)} [1 − σ_k(t)]
        σ_k = uncertainty estimate of scenario y_k (we use the coefficient of
        variation, per the paper's worked examples); q(t) = data-quality
        factor (coverage, freshness, consistency).

    m(t) = [OCI(t), CAI(t), CSI(t)]  — the diagnostic vector.

Interpretation (paper §4 thresholds): OCI < 0.8 signals semantic misalignment;
low CSI forces conservative action (the Manor's Chow-style gating, OC-14);
the three are interpreted JOINTLY (high CAI + low CSI = adequate explanation,
insufficient confidence).

Prior status: OCI/CAI/CSI were concept-for-formula with illustrative registry
floats (D10). This module makes them real code; the registry floats are
placeholders until values are produced from this implementation.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Sequence

# --- ontology constraints (Manor instantiation of C_Ω) -------------------------
# Each constraint is a predicate (ontology_state, interpreted_state) -> bool
# where True = satisfied (not violated). The paper's worked examples use
# 5-6 constraints; the Manor's first 5 mirror the aviation example's kinds.
Constraint = Callable[[Dict[str, object], Dict[str, float]], bool]


def _constraint_sensor_type(onto, state) -> bool:
    """(i) every active sensor has a declared type in the ontology."""
    declared = set(onto.get("sensor_types", {}))
    active = set(state.get("active_sensors", []))
    return active <= declared


def _constraint_part_whole(onto, state) -> bool:
    """(ii) part-whole relations respected: no part without its whole."""
    parts = set(state.get("parts", []))
    wholes = set(onto.get("wholes", {}))
    return parts <= wholes


def _constraint_unit_admissible(onto, state) -> bool:
    """(iii) every feature's unit is admissible for its corner."""
    units = onto.get("units", {})
    return all(u in units.get(corner, ()) for corner, u in state.get("feature_units", {}).items())


def _constraint_value_bounds(onto, state) -> bool:
    """(iv) every feature within its corner's declared bounds."""
    bounds = onto.get("bounds", {})
    for corner, val in state.get("feature_values", {}).items():
        lo, hi = bounds.get(corner, (-math.inf, math.inf))
        if not (lo <= val <= hi):
            return False
    return True


def _constraint_sensor_component_map(onto, state) -> bool:
    """(v) every sensor maps to exactly the components the ontology declares."""
    return state.get("sensor_map", {}) == onto.get("sensor_map", {})


DEFAULT_CONSTRAINTS: Dict[str, Constraint] = {
    "sensor_type": _constraint_sensor_type,
    "part_whole": _constraint_part_whole,
    "unit_admissible": _constraint_unit_admissible,
    "value_bounds": _constraint_value_bounds,
    "sensor_component_map": _constraint_sensor_component_map,
}


def default_similarity(a: Dict[str, float], b: Dict[str, float]) -> float:
    """Cosine similarity over the shared keys (the paper's sim(·,·), domain-specified)."""
    keys = set(a) & set(b)
    if not keys:
        return 0.0
    dot = sum(a[k] * b[k] for k in keys)
    na = math.sqrt(sum(a[k] ** 2 for k in keys))
    nb = math.sqrt(sum(b[k] ** 2 for k in keys))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return dot / (na * nb)


def coefficient_of_variation(values: Sequence[float]) -> float:
    """σ_k per the paper's worked examples: CV = std/mean of scenario estimates."""
    n = len(values)
    if n == 0:
        return 1.0  # no scenarios = maximal uncertainty
    mean = sum(values) / n
    if mean == 0.0:
        return 1.0
    var = sum((v - mean) ** 2 for v in values) / n
    return math.sqrt(var) / mean


@dataclass(frozen=True)
class TripleIndex:
    """m(t) = [OCI, CAI, CSI] — the diagnostic vector (paper eq.)."""

    oci: float
    cai: float
    csi: float

    def as_vector(self) -> List[float]:
        return [self.oci, self.cai, self.csi]

    @property
    def joint_read(self) -> str:
        """The paper's joint-interpretation note, made machine-readable."""
        if self.oci < 0.8:
            return "SEMANTIC_MISALIGNMENT"      # OCI below alarm bound
        if self.cai >= 0.8 and self.csi < 0.5:
            return "EXPLAINS_BUT_LOW_CONFIDENCE"  # adequate explanation, insufficient confidence
        if self.csi >= 0.5:
            return "CONFIDENT"                  # supports operational action
        return "CONSERVATIVE"                   # low CSI -> human judgment


def compute_triple_index(
    ontology: Dict[str, object],
    interpreted_state: Dict[str, object],
    scenarios: List[Dict[str, float]],
    data_quality: float,
    constraints: Dict[str, Constraint] | None = None,
    similarity: Callable[[Dict[str, float], Dict[str, float]], float] = default_similarity,
    cai_state: Dict[str, float] | None = None,
    exponential_dispersion: bool = False,
    dispersion_beta: float = 3.0,
) -> TripleIndex:
    """Compute OCI, CAI, CSI from the paper's definitions.

    Args:
        ontology: Ω — admissibility constraints context (sensor_types, units,
            bounds, sensor_map, wholes).
        interpreted_state: ŝ(t) — the structured state, including the
            constraint-relevant fields (active_sensors, parts, feature_units,
            feature_values, sensor_map) for OCI.
        scenarios: Y(t) — candidate scenario state vectors y_k(t).
        data_quality: q(t) ∈ [0,1] — sensor coverage/freshness/consistency.
        cai_state: the state VECTOR used for CAI similarity (the substrate
            posterior in the Manor). Defaults to interpreted_state filtered
            to its numeric fields (the paper's ŝ(t) plays both roles; the
            Manor separates the constraint context from the state vector).
        exponential_dispersion: use the paper's WORKED-EXAMPLE realization of
            CSI (σ_k = 1 − e^(−β·CV) over the scenario set, CSI = q·e^(−β·CV))
            instead of the formal per-scenario-CV definition. Reproduces the
            paper's Tables 3/5 numbers (β=3 aviation, β=2 urban).
        dispersion_beta: the domain penalty constant β (3 aviation, 2 urban).
    """
    cons = constraints or DEFAULT_CONSTRAINTS

    # --- OCI: fraction of satisfied constraints --------------------------------
    if not cons:
        oci = 1.0
    else:
        violated = sum(
            0 if c(ontology, interpreted_state) else 1 for c in cons.values()
        )
        oci = 1.0 - (violated / len(cons))

    # --- CAI: max similarity over scenarios ------------------------------------
    if cai_state is None:
        cai_state = {k: v for k, v in interpreted_state.items() if isinstance(v, (int, float))}
    cai = max((similarity(cai_state, y) for y in scenarios), default=0.0)
    cai = max(0.0, min(1.0, cai))

    # --- CSI: q(t) * max(1 - σ_k) over scenarios -------------------------------
    if not scenarios:
        csi = 0.0  # no scenarios -> no confidence
    else:
        if exponential_dispersion:
            # Paper's WORKED-EXAMPLE realization (Tables 3/5): σ_k = 1 − e^(−β·CV)
            # where CV is the dispersion across the scenario set's estimates and
            # β is the domain penalty constant (paper uses β=3 aviation, β=2 urban).
            # Then max(1−σ_k) = e^(−β·CV) and CSI = q·e^(−β·CV) — reproduces
            # 0.90·e^(−3·0.154) = 0.57 from the paper's own inputs.
            all_vals = [v for y in scenarios for v in y.values()]
            cv = coefficient_of_variation(all_vals)
            penalty = math.exp(-dispersion_beta * cv)
            best_certainty = penalty
        else:
            # Formal definition: σ_k = CV of scenario k's state vector.
            best_certainty = max(1.0 - coefficient_of_variation(list(y.values())) for y in scenarios)
        csi = data_quality * max(0.0, min(1.0, best_certainty))
    csi = max(0.0, min(1.0, csi))

    return TripleIndex(oci=round(oci, 4), cai=round(cai, 4), csi=round(csi, 4))


# --- CLI: worked-example self-check (the paper's aviation numbers, re-derived) ---
def main() -> int:
    # Aviation worked example (paper Table 3): 5 constraints, 4 satisfied -> OCI 0.80
    onto = {
        "sensor_types": {"HRV", "EDA", "TEMP"},
        "wholes": {"body", "chest"},
        "units": {"EM8": ("ms", "mV"), "EM10": ("lx", "dB")},
        "bounds": {"EM8": (0.0, 200.0), "EM10": (0.0, 1000.0)},
        "sensor_map": {"HRV": "chest"},
    }
    state = {
        "active_sensors": ["HRV", "EDA"],      # ok (both declared)
        "parts": ["chest"],                    # ok (chest ∈ wholes)
        "feature_units": {"EM8": "ms"},        # ok
        "feature_values": {"EM8": 23.2},       # ok
        "sensor_map": {"HRV": "wrist"},        # VIOLATED (declared: chest)
    }
    scenarios = [
        {"EM8": 0.3, "EM10": 0.4, "EM4": 0.5, "EM2": 0.5},
        {"EM8": 0.6, "EM10": 0.5, "EM4": 0.4, "EM2": 0.5},
        {"EM8": 0.9, "EM10": 0.7, "EM4": 0.3, "EM2": 0.6},
    ]
    # CAI state = the substrate posterior (the paper's ŝ(t) as state vector):
    # the Manor's estimate that scenario 2/3 should be nearest to.
    cai_state = {"EM8": 0.62, "EM10": 0.55, "EM4": 0.38, "EM2": 0.5}
    idx = compute_triple_index(onto, state, scenarios, data_quality=0.9, cai_state=cai_state)
    print(f"OCI = {idx.oci:.2f}  (paper: 4/5 = 0.80)")
    print(f"CAI = {idx.cai:.2f}  (max sim over scenarios)")
    print(f"CSI = {idx.csi:.2f}  (q * max(1-CV))")
    print(f"m(t) = {idx.as_vector()}")
    print(f"joint read: {idx.joint_read}")
    print("OCI check: 4 of 5 constraints satisfied (sensor_map violated) — matches paper.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
